###
GET {{baseUri}}/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "teste",
    "description": "Categoria criada via API/REST"
}

###
GET {{baseUri}}/categories/126 HTTP/1.1
Content-Type: application/json

###
PUT {{baseUri}}/categories/126 HTTP/1.1
Content-Type: application/json

{
    "description": "Categoria ATUALIZADA via API/REST"
}

###
DELETE {{baseUri}}/categories/130 HTTP/1.1
Content-Type: application/json