

###index
GET {{baseUri}}/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

###store
POST {{baseUri}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "mochila",
    "description": "preta"
}

###
GET {{baseUri}}/products/1 HTTP/1.1
Content-Type: application/json

###
PUT {{baseUri}}/products/1 HTTP/1.1
Content-Type: application/json

{
    "name": "caderno",
    "description": "Produto ATUALIZADA via API/REST"
}

###
DELETE {{baseUri}}/products/1 HTTP/1.1
Content-Type: application/json